# =============================================================================
# pyproject.toml — DSLR
# =============================================================================

[project]
name = "dslr"
version = "0.1.0"
description = ""
requires-python = ">=3.11"
dependencies = [
    "pandas>=3.0.6",
    "pytest>=9.1.1",
]
[tool.pytest.ini_options]
pythonpath = ["."]